### ISSUE TITLE
clang symbols not found

### ISSUE THREAD

**Issue by EddyHahn** [PlanTeam/MongoKitten#13]
Hi,
I have all the toolchains setup correctly. When I build from the command line I get a successful build. However when I try to build from Xcode the linker cannot link to the MongoKitten.swiftmodule.

Do I have to use a different version of clang?

Undefined symbols for architecture x86_64:
  "MongoKitten.Server.__allocating_init (at : Swift.String, port : Swift.Int, using : (username : Swift.String, password : Swift.String)?, automatically : Swift.Bool) throws -> MongoKitten.Server", referenced from:
      test.AppDelegate.applicationDidFinishLaunching (__ObjC.NSNotification) -> () in AppDelegate.o

ld: symbol(s) not found for architecture x86_64

Any idea? 

Thanks,

Eddy

**Comment by Obbut** [comment]
Are you using the Swift Development Snapshot 2016-03-24-a?

We (me and @Joannis) haven't used MongoKitten with a 'normal' OS X app project, we just `swift build --init` and then `swift build -X`. How did you set up your Xcode project to use MongoKitten?

**Comment by EddyHahn** [comment]
1) Yes, I am using Swift Development Snapshot 2016-03-24-a?
2) I did the same initialization swift build —init and swift build -X
3) Opened the project file and added to Build Settings -> Swift compiler - Search -> Import Path the path to .build/debug
4) Then I added just ten #iport MongoKitten to main.swift and built.  It was OK.
5) After that I added the example code to the main.swift  (connect to local mongo etc). Then the build failed. but the code complete did show the functions etc in the editor.

Eddy

**Comment by Joannis** [comment]
Could you post your `Package.swift`?

**Comment by Joannis** [comment]
On another note: Why are you adding an import path?
`swift build -X` should take care of that.

**Comment by Joannis** [comment]
@EddyHahn I've managed to reproduce the error. Tell me if I'm incorrect:

You've created a project in XCode. Added a package.swift with the required information. Then you've linked the `.build/debug` directory in the `import path`. Ran `swift build` and then you got the error, correct?

Currently XCode does not support SPM (Swift Package Manager) projects by default. So to solve this you'll have to generate the project differently. 

Create a directory with the name of your project:
`mkdir MyAwesomeProject`
Go in the direcotry:
`cd MyAwesomeProject`
Initialize the project:
`swift build --init`
Edit the Package.swift file to contain your dependencies:
`open Package.swift`
Save it (of course) and go back to the terminal
Create the XCode project using the Command Line tools
`swift build -X`
Enter the directory using `finder`
`open .`
 and open the XCode project by double-clicking it

This is not a bug in `MongoKitten` or any similar project. It's a missing feature in XCode that everyone is still waiting for. So I'll also write some instructions for when you're adding more dependencies:

Open the `Package.swift` using your editor and add the dependencies like above.
Open the terminal and enter your root-directory of the project again (same level as `Package.swift`)
Clean all build-directories:
`swift  build --clean dist`
And remake the project:
`swift build -X`

Now you can open the project again with XCode and you'll be set with your new dependencies.
If you're having issues for any reason within the XCode project at this point it's best to clean your XCode project. (CMD + K)

I hope this helps!

**Comment by EddyHahn** [comment]
Thanks!

I do not know what happened but this time around the swift build -X worked and all the packages now show up in Xcode.  Build did work swell and I can debug too!

Thank you Again!

Eddy

**Comment by Joannis** [comment]
No problem! Good luck with MongoKitten! Just enter another ticket if you need additional assistance.
