### ISSUE TITLE
No such module BSON in QueryBuilder.swift

### ISSUE THREAD

**Issue by mocode808** [PlanTeam/MongoKitten#21]
I was having issues using the Swift package manager it would cause my Xcode to crash.

So I added the .swift files for MongoKitten directly into my project and it seems to work fine but I can't compile it because I get an error on the import BSON statement saying no such modules exists.

How do I fix this?

**Comment by Obbut** [comment]
Are you targeting iOS or OS X? MongoKitten isn't tested on iOS.

I saw your [issue](https://github.com/PlanTeam/BSON/issues/6) on BSON. Were you able to resolve this?

If possible, I would recommend you to create your project as a SPM package (`swift build --init`) and to generate the Xcode project by running `swift build -X`. I have not tried to use MongoKitten without the Swift package manager.

**Comment by mocode808** [comment]
The SPM was crashing Xcode for me when attempting to use it with the snapshot so I am trying to install xCode 7.3.1_GM_Seed now to see if that will get the SPM working. 

And I am attempting to use this for iOS...IS there any chance it will work with iOS? If not do you know of any better recommendations for iOS ? I need to be able to use GridFS to upload videos :/

**Comment by Joannis** [comment]
@mocode808 The chance is there. And I'm uploading it in a bit

**Comment by mocode808** [comment]
I for the life of me cannot get the Swift Package Manager to work.

Would it be possible to get a tutorial on how to setup the Xcode project to work with Mongokitten without using the SPM?

It would be greatly appreciated. I am intending to use this for my Software engineering class final project and in my presentation at the end of the year I'll make sure to give a huge shoutout and credits to you guys for the assistance and framework.

**Comment by Joannis** [comment]
Honestly.. I've only used SPM. So I'll need to look into supporting Carthage for a package manager.. I can't promise you I'll have it fixed today since it's getting late (midnight). But tomorrow should work!

**Comment by mocode808** [comment]
If anything would I be able to send you my xCodeproject file and you add in MongoKitten using the SPM and then send the project back to me with MongoKitten already in it and all the imports for BSON handled? I would gladly pay you whatever price you request in Bitcoin please...

**Comment by mocode808** [comment]
I've got the SPM installed and when I run the command: swift build --version 

It returns Apple Swift Package Manager 0.1

However I went and created a Package.swift file and put the code you recommend in the readme file into my Package.swift and ran:
xcodebuild TOOLCHAINS=swift

and that returns an error saying no such module exists for PackageDescription in Package.swift.


Any suggestions to fix that?

**Comment by mocode808** [comment]
admins-Mac:~ admin$ swift build --version
Apple Swift Package Manager 0.1
admins-Mac:~ admin$ xcrun --find swift
/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain/usr/bin/swift
admins-Mac:~ admin$ swift --version
Apple Swift version 3.0-dev (LLVM 752e1430fc, Clang 1e6cba3ce3, Swift 56052cfe61)
Target: x86_64-apple-macosx10.9

**Comment by Joannis** [comment]
I think your swift snapshot isn't properly installed. The directory `/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain/usr/bin/` exists on my laptop and actually does contain a `swiftc` file.

**Comment by Joannis** [comment]
@mocode808 would you mind joining us on [Slack](http://orlandos.nl:3000) so I can help you more easily?
